### PR TITLE
curl.cainfo: cacert.pem

### PR DESCRIPTION
**Pull request by rubenvincenten**
Implemented this as a quick way to send messages if getting ssl errors.

### CODE REVIEW

**Comment by rubenvincenten** [comment]
I'm not sure why Travis is reporting here, as no travis.yml is in this repo(???)

**Comment by ivkos** [comment]
I'm not convinced we need to work around (mis)configuration related problems in this library. In my opinion, it's a much better idea to correctly set **curl.cainfo** in php.ini and fix pretty much all code that runs on PHP for Windows and relies on cURL's SSL.

As for Travis, it reports errors since it's not configured yet.

**Comment by codewise-nicolas** [comment]
would you consider
curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
too unsafe ?

**Comment by rubenvincenten** [comment]
@ivkos Sometimes on third party hosting they just have their PHP configured wrong, as you mentioned. And most of the time you can't change php.ini.

If you are not willing to pull in this PR, would you consider adding a addCurlCallback() method so people can set properties before running curl_exec?

That would also make @codewise-nicolas 's solution possible.

**Comment by codewise-nicolas** [comment]
In my local library I ended up doing this so that I could easily pass the library from server to server
if(!$this->_verifySSLPeerCurl){
        	curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);	//dont verify ssl certs against CA
 }

However I really like your idea @rubenvincenten about a callback to set curl parameters. Ill switch to that locally I think.

**Comment by ivkos** [comment]
@rubenvincenten @codewise-nicolas 
Could you please take a look at PR #36? Would you consider it a good solution or it could be done in a better way?

**Comment by codewise-nicolas** [comment]
Integrated locally, worked great.
Thanks

In my case I made this callback
$p->addCurlCallback(function($curl){ curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);	  });	//dont verify ssl certs against CA

**Pull request closed without merging**
