### PR TITLE
2.8 can't be used on 5.3, but syntax is valid for 5.3.

### PR DESCRIPTION
**Pull request by rubenvincenten**
My company's server is using php 5.3 so yeah :)

### CODE REVIEW

**Comment by rubenvincenten** [comment]
Uh, yeah, there is no 2.8 branch right now so travis is laming around...

**Comment by ivkos** [comment]
This would mess up all 2.x versions since 2.8.0 because they too require PHP 5.4. I don't think it's necessary to update such an old version now that we have 3.x.

I thought of something else: update the latest 2.x (i.e. 2.10) and lower the requirement so that Composer users on the **2.*** alias could use it on PHP 5.3.

Let me know what you think of this.

**Comment by rubenvincenten** [comment]
> I thought of something else: I could update the latest 2.x (i.e. 2.10) and lower the requirement so that Composer users on the 2.* alias could use the library on PHP 5.3.

Yes. This is exactly what I would like. I know utopia's would require everyone to be rewriting their own code, but the world is what it is. If you think 2.10 is compatible to PHP5.3 then by all means, push a minor version increase to it. Would be perfect.

**Comment by ivkos** [comment]
Here it is:
https://github.com/ivkos/Pushbullet-for-PHP/releases/tag/2.10.1

Thank you for the feedback. :)

**Pull request closed without merging**
